# Generated by Django 5.2.7 on 2025-10-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='upload_at',
            new_name='uploaded_at',
        ),
    ]
