# Generated by Django 5.2.7 on 2025-10-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_tag_photo_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
