# Generated by Django 5.2.7 on 2025-10-23 10:12

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_create_at_album_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='gallery.album')),
            ],
        ),
    ]
