# Generated by Django 5.2.7 on 2025-10-29 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_albumshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='camera_make',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='photo',
            name='camera_model',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='photo',
            name='exposure_time',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='photo',
            name='f_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='photo',
            name='focal_length',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='photo',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='gps_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='iso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['owner', 'album', 'uploaded_at'], name='gallery_pho_owner_i_e3b44a_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['taken_at'], name='gallery_pho_taken_a_4ce4df_idx'),
        ),
    ]
