# Generated by Django 5.2.7 on 2025-10-29 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_photo_camera_make_photo_camera_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('lang', models.CharField(default='zh', max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='ai_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='clip_vector',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='face_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='face_group_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='photo',
            name='vector_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='ai_label_ids',
            field=models.ManyToManyField(blank=True, related_name='photos', to='gallery.ailabel'),
        ),
        migrations.CreateModel(
            name='FaceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
